delete from jokes;
insert into jokes values(1,'What did the computer say to the other after a 16 hour car ride? ||Damn that was a hard drive||');
insert into jokes values(2,'Why couldn\'t the chili practice archery? ||He didn\'t Habanero||');
insert into jokes values(3,'My can opener broke ||Now it’s a *can’t* opener||');
insert into jokes values(4,'I hate people who talk about me behind my back ||They discussed me||');
insert into jokes values(5,'I\'m afraid for the calendar. ||Its days are numbered||');
insert into jokes values(6,'My wife said I should do lunges to stay in shape. ||That would be a big step forward||');
insert into jokes values(7,'Why do fathers take an extra pair of socks when they go golfing? ||In case they get a hole in one||');
insert into jokes values(8,'Singing in the shower is fun until you get soap in your mouth. ||Then it\'s a soap opera||');
insert into jokes values(9,'What do a tick and the Eiffel Tower have in common? ||They\'re both Paris sites||');
insert into jokes values(10,'What do you call a fish wearing a bowtie? ||So*fish*ticated||');
insert into jokes values(11,'How do you follow Will Smith in the snow? ||You follow the fresh prints||');
insert into jokes values(12,'If April showers bring May flowers, what do May flowers bring? ||Pilgrims||');
insert into jokes values(13,'I thought the dryer was shrinking my clothes. ||Turns out it was the refrigerator all along||');
insert into jokes values(14,'What do you call a factory that makes okay products? ||A satisfactory||');
insert into jokes values(15,'Dear Math, grow up and solve your own problems');
insert into jokes values(16,'What did the janitor say when he jumped out of the closet? ||Supplies||');
insert into jokes values(17,'Have you heard about the chocolate record player? ||It sounds pretty sweet||');
insert into jokes values(18,'What did the ocean say to the beach? ||Nothing, it just *waved*||');
insert into jokes values(19,'Why do seagulls fly over the ocean? ||Because if they flew over the bay, we\'d call them *baygels*||');
insert into jokes values(20,'I only know 25 letters of the alphabet. ||I don\'t know y||');
insert into jokes values(21,'How does the moon cut his hair? ||Eclipse it||');
insert into jokes values(22,'What did one wall say to the other? ||I\'ll meet you at the corner||');
insert into jokes values(23,'What did the zero say to the eight? ||That belt looks good on you||');
insert into jokes values(24,'A skeleton walks into a bar and says, Hey, bartender. ||I\'ll have one beer and a mop||');
insert into jokes values(25,'Where do fruits go on vacation? ||*Pear*-is||');
insert into jokes values(26,'I asked my dog what\'s two minus two. He said ||nothing||');
insert into jokes values(27,'What did Baby Corn say to Mama Corn? ||Where\'s Pop Corn?||');
insert into jokes values(28,'What\'s the best thing about Switzerland? I don\'t know, but ||the flag is a big plus||');
insert into jokes values(29,'What does a sprinter eat before a race? ||Nothing, they fast||');
insert into jokes values(30,'Where do you learn to make a banana split? ||Sundae school||');
insert into jokes values(31,'What has more letters than the alphabet? ||The post office||');
insert into jokes values(32,'Dad, did you get a haircut? ||No, I got them all cut||');
insert into jokes values(33,'What do you call a poor Santa Claus? ||St. Nickel-less||');
insert into jokes values(34,'I got carded at a liquor store, and my Blockbuster card accidentally fell out. ||The cashier said never mind||');
insert into jokes values(35,'Where do boats go when they\'re sick? ||To the boat doc||');
insert into jokes values(36,'I don\'t trust those trees. ||They seem kind of shady||');
insert into jokes values(37,'My wife is really mad at the fact that I have no sense of direction. ||So I packed up my stuff and right||');
insert into jokes values(38,'How do you get a squirrel to like you? ||Act like a nut||');
insert into jokes values(39,'Why don\'t eggs tell jokes? ||They\'d crack each other up||');
insert into jokes values(40,'I don\'t trust stairs. ||They\'re always up to something||');
insert into jokes values(41,'What do you call someone with no body and no nose? ||Nobody knows||');
insert into jokes values(42,'Did you hear the rumor about butter? ||Well, I\'m not going to spread it||');
insert into jokes values(43,'Why couldn\'t the bicycle stand up by itself? ||It was two tired||');
insert into jokes values(44,'What did one hat say to the other? ||Stay here! I\'m going on ahead||');
insert into jokes values(45,'Why did Billy get fired from the banana factory? ||He kept throwing away the bent ones||');
insert into jokes values(46,'Why can\'t a nose be 12 inches long? ||Because then it would be a foot||');
insert into jokes values(47,'What does a lemon say when it answers the phone? ||Yellow||');
insert into jokes values(48,'This graveyard looks overcrowded. ||People must be *dying* to get in||');
insert into jokes values(49,'What kind of car does an egg drive? ||A *yolks*wagen||');
insert into jokes values(50,'How do you make 7 even? ||Take away the s||');
insert into jokes values(51,'How does a taco say grace? ||Lettuce pray||');
insert into jokes values(52,'What time did the man go to the dentist? ||Tooth hurt-y||');
insert into jokes values(53,'Why didn\'t the skeleton climb the mountain? ||It didn\'t have the guts||');
insert into jokes values(54,'What do you call it when a snowman throws a tantrum? ||A meltdown||');
insert into jokes values(55,'How many tickles does it take to make an octopus laugh? ||Ten tickles||');
insert into jokes values(56,'I have a joke about chemistry, ||but I don\'t think it will get a reaction||');
insert into jokes values(57,'What concert costs just 45 cents? ||50 Cent featuring Nickelback||');
insert into jokes values(58,'What does a bee use to brush its hair? ||A honeycomb||');
insert into jokes values(59,'How do you make a tissue dance? ||You put a little boogie in it||');
insert into jokes values(60,'Why did the math book look so sad? ||Because of all of its problems||');
insert into jokes values(61,'What do you call cheese that isn\'t yours? ||Nacho cheese||');
insert into jokes values(62,'My dad told me a joke about boxing. ||I guess I missed the punch line||.');
insert into jokes values(63,'What kind of shoes do ninjas wear? ||Sneakers||');
insert into jokes values(64,'How does a penguin build its house? ||Igloos it together||');
insert into jokes values(65,'I used to be addicted to soap, but I\'m clean now');
insert into jokes values(66,'A guy walks into a bar and he was disqualified from the limbo contest');
insert into jokes values(67,'You think swimming with sharks is expensive? Swimming with sharks cost me an arm and a leg');
insert into jokes values(68,'When two vegans get in an argument, is it still called a beef?');
insert into jokes values(69,'I ordered a chicken and an egg from Amazon. I\'ll let you know');
insert into jokes values(70,'That car looks nice but the muffler seems exhausted');
insert into jokes values(71,'Shout out to my fingers. I can count on all of them');
insert into jokes values(72,'You know, people say they pick their nose, but I feel like I was just born with mine');
insert into jokes values(73,'If a child refuses to nap, are they guilty of resisting a rest?');
insert into jokes values(74,'What country\'s capital is growing the fastest? ||Ireland. Every day it\'s Dublin||');
insert into jokes values(75,'I once had a dream I was floating in an ocean of orange soda. It was more of a fanta sea');
insert into jokes values(76,'Did you hear about the kidnapping at school? ||It\'s okay, he woke up||');
insert into jokes values(77,'A cheeseburger walks into a bar. ||The bartender says, Sorry, we don\'t serve food here||');
insert into jokes values(78,'I once got fired from a canned juice company. ||Apparently I couldn\'t concentrate||');
insert into jokes values(79,'I used to play piano by ear. ||Now I use my hands||');
insert into jokes values(80,'Have you ever tried to catch a fog? ||I tried yesterday but I mist||');
insert into jokes values(81,'I\'m on a seafood diet I see food and I eat it');
insert into jokes values(82,'Why did the scarecrow win an award? ||Because he was outstanding in his field||');
insert into jokes values(83,'I made a pencil with two erasers. ||It was pointless||');
insert into jokes values(84,'I\'m reading a book about anti-gravity. ||It\'s impossible to put down||');
insert into jokes values(85,'Did you hear about the guy who invented the knock-knock joke? ||He won the *no-bell* prize||');
insert into jokes values(86,'I\'ve got a great joke about construction, but I\'m still working on it');
insert into jokes values(87,'I used to hate facial hair but then it *grew* on me');
insert into jokes values(88,'I decided to sell my vacuum cleaner it was just gathering dust');
insert into jokes values(89,'I had a neck brace fitted years ago and I\'ve never looked back since');
insert into jokes values(90,'What\'s brown and sticky? ||A stick||');
insert into jokes values(91,'Why can\'t you hear a psychiatrist using the bathroom? ||Because the *P* is silent||');
insert into jokes values(92,'What do you call an elephant that doesn\'t matter? ||An irrelephant||');
insert into jokes values(93,'What do you get from a pampered cow? ||Spoiled milk||');
insert into jokes values(94,'I like telling Dad jokes. Sometimes he laughs');
insert into jokes values(95,'What\'s the best smelling insect? ||A deodor-ant||');
insert into jokes values(96,'I used to be a personal trainer. ||Then I gave my too weak notice||');
insert into jokes values(97,'Did I tell you the time I fell in love during a backflip? ||I was heels over head||');
insert into jokes values(98,'It takes guts to be an organ donor');
insert into jokes values(99,'If you see a crime at an Apple Store, does that make you an iWitness?');
insert into jokes values(100,'I\'m so good at sleeping, I can do it with my eyes closed!');
insert into jokes values(101,'I was going to tell a time-traveling joke, but you guys didn\'t like it');
insert into jokes values(102,'What do you call a fake noodle? ||An impasta||');
insert into jokes values(103,'What do you call a belt made of watches? ||A waist of time||');
insert into jokes values(104,'What happens when a strawberry gets run over crossing the street? ||Traffic jam||');
insert into jokes values(105,'What do you call two monkeys that share an Amazon account? ||Prime mates||');
insert into jokes values(106,'What do you call a pony with a sore throat? ||A little hoarse||');
insert into jokes values(107,'Where do math teachers go on vacation? ||Times Square||');
insert into jokes values(108,'Whenever I try to eat healthy, a chocolate bar looks at me and Snickers');
insert into jokes values(109,'What does garlic do when it gets hot? ||It takes its cloves off||');
insert into jokes values(110,'What\'s a robot\'s favorite snack? ||Computer chips||');
insert into jokes values(111,'How much does it cost Santa to park his sleigh? ||Nothing, it\'s on the house||');
insert into jokes values(112,'Mountains aren\'t just funny. ||They\'re hill areas||');
insert into jokes values(113,'What do clouds wear? ||Thunderwear||');
insert into jokes values(114,'Why are piggy banks so wise? ||They\'re filled with common cents||');
insert into jokes values(115,'Why is Peter Pan always flying? ||He neverlands||');
insert into jokes values(116,'How do you get a good price on a sled? ||You have toboggan||');
insert into jokes values(117,'How can you tell if a tree is a dogwood tree? ||By its bark||');
insert into jokes values(118,'It\'s inappropriate to make a dad joke if you\'re not a dad. ||It\'s a faux pa||');
insert into jokes values(119,'What do you call a hot dog on wheels? ||Fast food||');
insert into jokes values(120,'Where do young trees go to learn? ||Elementree school||');
insert into jokes values(121,'Did you hear about the circus fire? ||It was in tents||');
insert into jokes values(122,'Can February March? ||No, but April May||');
insert into jokes values(123,'How do lawyers say goodbye? ||We\'ll be suing ya||');
insert into jokes values(124,'Wanna hear a joke about paper? ||Never mind it\'s tearable||');
insert into jokes values(125,'What\'s the best way to watch a fly fishing tournament? ||Live stream||');
insert into jokes values(126,'Spring is here! ||I got so excited I wet my plants||');
insert into jokes values(127,'I could tell a joke about pizza, ||but it\'s a little cheesy||');
insert into jokes values(128,'Don\'t trust atoms. ||They make up everything||');
insert into jokes values(129,'When does a joke become a dad joke? ||When it becomes apparent||');
insert into jokes values(130,'I wouldn\'t buy anything with velcro. ||It\'s a total rip-off||');
insert into jokes values(131,'What’s an astronaut’s favorite part of a computer? ||The space bar||');
insert into jokes values(132,'I don\'t play soccer because I enjoy the sport. ||I\'m just doing it for kicks||');
insert into jokes values(133,'Why are elevator jokes so classic and good? ||They work on many levels||');
insert into jokes values(134,'Which state has the most streets? ||Rhode Island||');
insert into jokes values(135,'What did the coffee report to the police? ||A mugging||');
insert into jokes values(136,'What did the fish say when he hit the wall? ||Dam||');
insert into jokes values(137,'Is this pool safe for diving? ||It deep ends||');
insert into jokes values(138,'I saw an old man fall into a well today. ||I guess he couldn\'t see that well||');
insert into jokes values(139,'Which bear is the most condescending? ||A pan-duh||');
insert into jokes values(140,'What kind of noise does a witch’s vehicle make? ||Brrrroooom, brrroooom||');
insert into jokes values(141,'How do you get a country girl’s attention? ||A tractor||');
insert into jokes values(142,'What do you call it when a group of apes starts a company? ||Monkey business||');
insert into jokes values(143,'What kind of drink can be bitter and sweet? ||Reali-tea||');
insert into jokes values(144,'Want to know why nurses like red crayons? ||Sometimes they have to draw blood||');
insert into jokes values(145,'Want to hear a joke about Nitrus Oxide? ||NO||');
insert into jokes values(146,'What do you do with a dead chemist? ||Barium||');
insert into jokes values(147,'What do you do with a sick chemist? ||Helium||');
insert into jokes values(148,'What did the green grape say to the purple grape? ||Breathe||');
insert into jokes values(149,'Who would win a fight between a shark and an octopus? ||The octopus. He\'s well-armed||');
insert into jokes values(150,'Did you hear about the blue ship that sank in the Red Sea? ||Apparently the survivors are marooned||');
insert into jokes values(151,'What did the mushroom say on his date? ||I\'m a real fungi||');
insert into jokes values(152,'I gave all my old batteries away today. ||No charge!||');
insert into jokes values(153,'Why was the sarafi cat disqualified from the race? ||He was a cheetah||');
insert into jokes values(154,'What do you call a group of killer whales playing instruments? ||An orca-stra||');
insert into jokes values(155,'I am terrified of elevators. ||I\'m going to start taking steps to avoid them||');
insert into jokes values(156,'Imagine a world without geometry. ||Life would be pointless||');
insert into jokes values(157,'What did the vet say about the sick tiger? ||I don\'t think he\'s feline well||');
insert into jokes values(158,'Why do lobsters never give to charity? ||Because they\'re shellfish||');
insert into jokes values(159,'Did you hear about the lady who stole the calendar? ||She got 12 months||');
insert into jokes values(160,'I wanted to buy some camouflage gear the other day. ||But I couldn\'t find any||');
insert into jokes values(161,'How do you organize a NASA party? ||You planet||');
insert into jokes values(162,'Did you hear about the two antennas who got married? ||The ceremony was boring, but the reception was great||');
insert into jokes values(163,'My kid asked me to put his shoes on, ||but I don't think they'll fit me||');
insert into jokes values(164,'My kids keep telling me to stop pretending to be butter. ||But I\'m on a roll now||');
insert into jokes values(165,'How does Darth Vader like his morning bagel toasted? ||On the dark side||');
insert into jokes values(166,'How do inmates call each other? ||They use cell phones||');
insert into jokes values(167,'What do you call an old person with really good hearing? ||Deaf defying||');
insert into jokes values(168,'Guess what chore I\'m doing today? ||Vacuuming. It sucks||');
insert into jokes values(169,'What do you call cheese that isn\'t yours? ||Nacho cheese||');
insert into jokes values(170,'Why couldn\'t the motorcycle stand on its own? ||It was two tired||');
insert into jokes values(171,'A jumper cable walks into a diner. ||The waitress says, I\'ll serve you, just don\'t start anything||');
insert into jokes values(172,'What happened to the mermaid at the dance club? ||She pulled a mussel||');
insert into jokes values(173,'What did the rock climber name his son? ||Cliff||');
insert into jokes values(174,'Why did the scarecrow win the Scarecrow of the Year Award? ||He was outstanding in his field||');
insert into jokes values(175,'What is the best time on a clock? ||6:30. Hands down.||');
insert into jokes values(176,'I went bald years ago, but I still carry around my comb. ||I just can\'t part with it||');
insert into jokes values(177,'I\'m not a big fan of sushi. ||Seems a little fishy to me||');
insert into jokes values(178,'My doctor told me I should try an all-cashew diet. ||I said, But Doc, that\'s just nuts!||');
insert into jokes values(179,'Why did the man quit his job at the show recycing plant? ||It was sole destroying||');
insert into jokes values(180,'How many apples grow on a tree? ||All of them||');
insert into jokes values(181,'I went to the new diner on the moon. ||Great food. No atmosphere.||');
insert into jokes values(182,'What did one goldfish say to the other goldfish in the tank? ||Any idea how to drive this thing?||');
insert into jokes values(183,'What do you call a man with one rubber toe? ||Roberto||');
insert into jokes values(184,'I didn\'t want to believe my wife was stealing from her job in road work. ||But when I got home, all the signs were there||');
insert into jokes values(185,'Never trust a caricature. ||They\'re so sketchy||');
insert into jokes values(186,'I had planned to be a banker. ||But I lost interest||');
insert into jokes values(187,'I was just diagnosed a colorblind. ||It really came out of the purple||');
insert into jokes values(188,'I really need to fix my watch. ||But I never seem to have the time||');
insert into jokes values(189,'I used to work at the calendar factory. ||But I got fired for taking a couple days off||');
insert into jokes values(190,'What kind of key opens a banana? ||A monkey||');
insert into jokes values(191,'What a beautiful wedding. ||Even the cake was in tiers||');
insert into jokes values(192,'Did you hear about the explosion at the cake factory? ||All that was left was de-brie||');
insert into jokes values(193,'Whatever you do, don\'t trust an atom. ||They make up everything||');
insert into jokes values(194,'Peppers are so annoying. ||They get jalapeño face||');
insert into jokes values(195,'I\'d like to give a shoutout to all the sidewalks. ||They keep me off the streets||');
insert into jokes values(196,'What did the police molecule say during the interrogation? ||I\'ve got my ion you||');
insert into jokes values(197,'What is a vampire\'s favorite fruit? ||A neck-tarine||');
insert into jokes values(198,'Have you heard of a shovel? ||What a groundbreaking invention||');
insert into jokes values(199,'How does flower greet its baby? ||Hey, Bud!||');
insert into jokes values(200,'Did you hear about the bakery that burned down? ||That business is toast now||');
insert into jokes values(201,'What kind of animal is always at the World Series? ||A bat||');
insert into jokes values(202,'Why can't Elsa have a balloon? ||She'll let it go||');
insert into jokes values(203,'Where can you always find the thing you lost? ||The last place you look||');
insert into jokes values(204,'What did the nut say after catching a cold? ||Cashew||');
insert into jokes values(205,'What is Forrest Gump\'s computer password? ||1Forrest1||');
insert into jokes values(206,'Want to hear a construction joke? ||I\'m working on it||');
insert into jokes values(207,'What veggies do pirate hate most? ||Leeks||');
insert into jokes values(208,'Why do dogs make the worst dance partners? ||They have two left feet||');
insert into jokes values(209,'What dinosaur had the best vocabulary? ||The thesaurus||');
insert into jokes values(210,'What time is it when an elephant sits on the fence? ||Time to get a new fence||');
insert into jokes values(211,'Why didn\'t the orange win the race? ||It ran out of juice||');
